### PR TITLE
GH actions: add custom runners to parallelize jobs

### PR DESCRIPTION
**Pull request by acomodi**
This PR is built after the development performed in https://github.com/SymbiFlow/fpga-tool-perf/pull/380, https://github.com/SymbiFlow/fpga-tool-perf/pull/379 and https://github.com/SymbiFlow/fpga-tool-perf/pull/378.

It adds the possibility to run all the test suite in parallel, one task per runner, drastically reducing the CI cycle time. At the end of all the runs, the results are collected and aggregated and pushed to a GCP bucket.

The GH pages CI grabs all the results from the bucket and generates the dashboard, as it previously happened.

### CODE REVIEW

**Comment by kgugala** [comment]
we should drop kokoro in this PR

**Comment by acomodi** [comment]
> we should drop kokoro in this PR

Yeah, we may do this, and it should also happen on the kokoro side, as CI will still run and it won't find the kokoro configuration file to run the job.

**Comment by acomodi** [comment]
@mithro As we transition to GH custom runners, the `countinuous`, `nightly` and `presubmit` instances of kokoro need to be removed to have green CI

**Review by mithro — COMMENTED** [review]
Please land this in multiple steps;
 (a) Add the Github Actions stuff.
 (b) Wait a bit and confirm both are working together.
 (c) Get a Googler to remove the Kokoro config.
 (d) Remove the kokoro configurations.

**Comment by acomodi** [comment]
@mithro Ok, we have restored Kokoro, we'll merge this one and check that everything is stable and proceed with point c) and d)

**Pull request merged**
