### PR TITLE
Implemented New --list-combinations Argument

### LINKED ISSUE #202: Add utility to list all project, toolchain, board combinations
It would be good to have a utility script that displays all the different combinations of <project, toolchain, board> tuples combinations. 

This would make easier to understand which tests are available.

### PR DESCRIPTION
**Pull request by ryancj14**
This pull request fixes #202, adding a new `--list-combinations` argument, which lists all of the combinations of <project, toolchain, board> available to run in `fpga-tool-perf`. Example:
```
$ python3 fpgaperf.py --list-combinations
(Project, Toolchain, Board)
---------------------------
(baselitex, vivado, arty)
(baselitex, vivado-yosys, arty)
(baselitex, nextpnr-xilinx, arty)
(baselitex, vpr, arty)
(baselitex, vpr-fasm2bels, arty)
(blinky, vpr, arty)
(blinky, vpr-fasm2bels, arty)
(blinky, nextpnr-xilinx, arty)
(blinky, nextpnr-xilinx-fasm2bels, arty)
(blinky, vivado, arty)
(blinky, vivado-yosys, arty)
(hamsternz-hdmi, vivado, nexys)
(ibex, vpr, arty)
(ibex, vpr-fasm2bels, arty)
(ibex, vivado, arty)
(ibex, vivado-yosys, arty)
(murax, vpr, basys3)
(murax, vpr-fasm2bels, basys3)
(murax, nextpnr-xilinx, basys3)
(murax, vivado-yosys, basys3)
(murax, vivado, basys3)
(oneblink, vpr, arty)
(oneblink, vpr, basys3)
(oneblink, vpr, zybo)
(oneblink, vpr-fasm2bels, arty)
(oneblink, vpr-fasm2bels, basys3)
(oneblink, vpr-fasm2bels, zybo)
(oneblink, vivado, arty)
(oneblink, vivado, basys3)
(oneblink, vivado, zybo)
(oneblink, vivado-yosys, arty)
(oneblink, vivado-yosys, basys3)
(oneblink, vivado-yosys, zybo)
(oneblink, nextpnr-ice40, icebreaker)
(picorv32, vivado, arty)
(picorv32, vivado, zybo)
(picorv32, vivado-yosys, arty)
(picorv32, vivado-yosys, zybo)
(picorv32, vpr, arty)
(picorv32, vpr, zybo)
(picorv32, vpr-fasm2bels, arty)
(picorv32, vpr-fasm2bels, zybo)
(picosoc, vpr, basys3)
(picosoc, vpr-fasm2bels, basys3)
(picosoc, nextpnr-xilinx, basys3)
(picosoc, vivado, basys3)
(picosoc, vivado-yosys, basys3)
(picosoc-simpleuart, vivado, basys3)
(picosoc-simpleuart, vivado-yosys, basys3)
(picosoc-simpleuart, vpr, basys3)
(picosoc-simpleuart, vpr-fasm2bels, basys3)
(picosoc-spimemio, vivado, basys3)
(picosoc-spimemio, vivado-yosys, basys3)
(picosoc-spimemio, vpr, basys3)
(picosoc-spimemio, vpr-fasm2bels, basys3)
(vexriscv, vivado, basys3)
(vexriscv, vivado-yosys, basys3)
(vexriscv, vpr, basys3)
(vexriscv, vpr-fasm2bels, basys3)
(vexriscv-smp, vivado, arty)
```
Let me know if there are any changes that need to be made to my implementation.

### CODE REVIEW

**Comment by acomodi** [comment]
Thanks for the PR @ryancj14!
I have been thinking about this and it would be even better probably to have an output table in this form:

```
+-----------+----------------+-------+-----------+
| Design    | Toolchain      | Board |  Status   |
+-----------+----------------+-------+-----------+
| baselitex | vpr            | arty  | Supported |
+-----------+----------------+-------+-----------+
| baselitex | vpr            | zybo  | Missing   |
+-----------+----------------+-------+-----------+
| murax     | nextpnr-xilinx | arty  | Missing   |
+-----------+----------------+-------+-----------+
| murax     | nextpnr-xilinx | zybo  | Supported |
+-----------+----------------+-------+-----------+
```

And this for each design toolchain and board available.

There is a code example that generates a very similar table here: https://github.com/SymbiFlow/fpga-tool-perf/blob/4e26633ff36db1ace064074ac1f4dbca42f75d9e/exhaust.py#L33-L80

**Comment by ryancj14** [comment]
Do you want the nexys board and the icebreaker board to be represented? Because each of those are only supported for one project. Similarly, there are lots of toolchains that are only supported in one or two projects. It seems like what would be printed if it included every single combination would be more of what isn't available to run than what is. But, if one of our goals is to add each of those combinations, than having a list like this would indeed be very useful.

 I'm assuming what you are asking for right now is something like below. How does this look? This is a very lengthy output, which I have shortened to represent just a few projects. Also, I still need to add a line between each entry like you have in your example, but haven't yet discovered how to do that. I just wanted to ask these questions first.
```
$ python3 fpgaperf.py --list-combinations
+--------------------+--------------------------+------------+-----------+
| Project            | Toolchain                | Board      | Status    |
+--------------------+--------------------------+------------+-----------+
| baselitex          | icecube2-lse             | arty       | Missing   |
| baselitex          | icecube2-lse             | basys3     | Missing   |
| baselitex          | icecube2-lse             | icebreaker | Missing   |
| baselitex          | icecube2-lse             | nexys      | Missing   |
| baselitex          | icecube2-lse             | zybo       | Missing   |
| baselitex          | icecube2-synpro          | arty       | Missing   |
| baselitex          | icecube2-synpro          | basys3     | Missing   |
| baselitex          | icecube2-synpro          | icebreaker | Missing   |
| baselitex          | icecube2-synpro          | nexys      | Missing   |
| baselitex          | icecube2-synpro          | zybo       | Missing   |
| baselitex          | icecube2-yosys           | arty       | Missing   |
| baselitex          | icecube2-yosys           | basys3     | Missing   |
| baselitex          | icecube2-yosys           | icebreaker | Missing   |
| baselitex          | icecube2-yosys           | nexys      | Missing   |
| baselitex          | icecube2-yosys           | zybo       | Missing   |
| baselitex          | nextpnr-ice40            | arty       | Missing   |
| baselitex          | nextpnr-ice40            | basys3     | Missing   |
| baselitex          | nextpnr-ice40            | icebreaker | Missing   |
| baselitex          | nextpnr-ice40            | nexys      | Missing   |
| baselitex          | nextpnr-ice40            | zybo       | Missing   |
| baselitex          | nextpnr-xilinx           | arty       | Supported |
| baselitex          | nextpnr-xilinx           | basys3     | Missing   |
| baselitex          | nextpnr-xilinx           | icebreaker | Missing   |
| baselitex          | nextpnr-xilinx           | nexys      | Missing   |
| baselitex          | nextpnr-xilinx           | zybo       | Missing   |
| baselitex          | nextpnr-xilinx-fasm2bels | arty       | Missing   |
| baselitex          | nextpnr-xilinx-fasm2bels | basys3     | Missing   |
| baselitex          | nextpnr-xilinx-fasm2bels | icebreaker | Missing   |
| baselitex          | nextpnr-xilinx-fasm2bels | nexys      | Missing   |
| baselitex          | nextpnr-xilinx-fasm2bels | zybo       | Missing   |
| baselitex          | radiant-lse              | arty       | Missing   |
| baselitex          | radiant-lse              | basys3     | Missing   |
| baselitex          | radiant-lse              | icebreaker | Missing   |
| baselitex          | radiant-lse              | nexys      | Missing   |
| baselitex          | radiant-lse              | zybo       | Missing   |
| baselitex          | radiant-synpro           | arty       | Missing   |
| baselitex          | radiant-synpro           | basys3     | Missing   |
| baselitex          | radiant-synpro           | icebreaker | Missing   |
| baselitex          | radiant-synpro           | nexys      | Missing   |
| baselitex          | radiant-synpro           | zybo       | Missing   |
| baselitex          | vivado                   | arty       | Supported |
| baselitex          | vivado                   | basys3     | Missing   |
| baselitex          | vivado                   | icebreaker | Missing   |
| baselitex          | vivado                   | nexys      | Missing   |
| baselitex          | vivado                   | zybo       | Missing   |
| baselitex          | vivado-yosys             | arty       | Supported |
| baselitex          | vivado-yosys             | basys3     | Missing   |
| baselitex          | vivado-yosys             | icebreaker | Missing   |
| baselitex          | vivado-yosys             | nexys      | Missing   |
| baselitex          | vivado-yosys             | zybo       | Missing   |
| baselitex          | vpr                      | arty       | Supported |
| baselitex          | vpr                      | basys3     | Missing   |
| baselitex          | vpr                      | icebreaker | Missing   |
| baselitex          | vpr                      | nexys      | Missing   |
| baselitex          | vpr                      | zybo       | Missing   |
| baselitex          | vpr-fasm2bels            | arty       | Supported |
| baselitex          | vpr-fasm2bels            | basys3     | Missing   |
| baselitex          | vpr-fasm2bels            | icebreaker | Missing   |
| baselitex          | vpr-fasm2bels            | nexys      | Missing   |
| baselitex          | vpr-fasm2bels            | zybo       | Missing   |
| blinky             | icecube2-lse             | arty       | Missing   |
| blinky             | icecube2-lse             | basys3     | Missing   |
| blinky             | icecube2-lse             | icebreaker | Missing   |
| blinky             | icecube2-lse             | nexys      | Missing   |
| blinky             | icecube2-lse             | zybo       | Missing   |
| blinky             | icecube2-synpro          | arty       | Missing   |
| blinky             | icecube2-synpro          | basys3     | Missing   |
| blinky             | icecube2-synpro          | icebreaker | Missing   |
| blinky             | icecube2-synpro          | nexys      | Missing   |
| blinky             | icecube2-synpro          | zybo       | Missing   |
| blinky             | icecube2-yosys           | arty       | Missing   |
| blinky             | icecube2-yosys           | basys3     | Missing   |
| blinky             | icecube2-yosys           | icebreaker | Missing   |
| blinky             | icecube2-yosys           | nexys      | Missing   |
| blinky             | icecube2-yosys           | zybo       | Missing   |
| blinky             | nextpnr-ice40            | arty       | Missing   |
| blinky             | nextpnr-ice40            | basys3     | Missing   |
| blinky             | nextpnr-ice40            | icebreaker | Missing   |
| blinky             | nextpnr-ice40            | nexys      | Missing   |
| blinky             | nextpnr-ice40            | zybo       | Missing   |
| blinky             | nextpnr-xilinx           | arty       | Supported |
| blinky             | nextpnr-xilinx           | basys3     | Missing   |
| blinky             | nextpnr-xilinx           | icebreaker | Missing   |
| blinky             | nextpnr-xilinx           | nexys      | Missing   |
| blinky             | nextpnr-xilinx           | zybo       | Missing   |
| blinky             | nextpnr-xilinx-fasm2bels | arty       | Supported |
| blinky             | nextpnr-xilinx-fasm2bels | basys3     | Missing   |
| blinky             | nextpnr-xilinx-fasm2bels | icebreaker | Missing   |
| blinky             | nextpnr-xilinx-fasm2bels | nexys      | Missing   |
| blinky             | nextpnr-xilinx-fasm2bels | zybo       | Missing   |
| blinky             | radiant-lse              | arty       | Missing   |
| blinky             | radiant-lse              | basys3     | Missing   |
| blinky             | radiant-lse              | icebreaker | Missing   |
| blinky             | radiant-lse              | nexys      | Missing   |
| blinky             | radiant-lse              | zybo       | Missing   |
| blinky             | radiant-synpro           | arty       | Missing   |
| blinky             | radiant-synpro           | basys3     | Missing   |
| blinky             | radiant-synpro           | icebreaker | Missing   |
| blinky             | radiant-synpro           | nexys      | Missing   |
| blinky             | radiant-synpro           | zybo       | Missing   |
| blinky             | vivado                   | arty       | Supported |
| blinky             | vivado                   | basys3     | Missing   |
| blinky             | vivado                   | icebreaker | Missing   |
| blinky             | vivado                   | nexys      | Missing   |
| blinky             | vivado                   | zybo       | Missing   |
| blinky             | vivado-yosys             | arty       | Supported |
| blinky             | vivado-yosys             | basys3     | Missing   |
| blinky             | vivado-yosys             | icebreaker | Missing   |
| blinky             | vivado-yosys             | nexys      | Missing   |
| blinky             | vivado-yosys             | zybo       | Missing   |
| blinky             | vpr                      | arty       | Supported |
| blinky             | vpr                      | basys3     | Missing   |
| blinky             | vpr                      | icebreaker | Missing   |
| blinky             | vpr                      | nexys      | Missing   |
| blinky             | vpr                      | zybo       | Missing   |
| blinky             | vpr-fasm2bels            | arty       | Supported |
| blinky             | vpr-fasm2bels            | basys3     | Missing   |
| blinky             | vpr-fasm2bels            | icebreaker | Missing   |
| blinky             | vpr-fasm2bels            | nexys      | Missing   |
| blinky             | vpr-fasm2bels            | zybo       | Missing   |
| hamsternz-hdmi     | icecube2-lse             | arty       | Missing   |
| hamsternz-hdmi     | icecube2-lse             | basys3     | Missing   |
.....
| picosoc-spimemio   | vpr-fasm2bels            | nexys      | Missing   |
| picosoc-spimemio   | vpr-fasm2bels            | zybo       | Missing   |
| vexriscv           | icecube2-lse             | arty       | Missing   |
| vexriscv           | icecube2-lse             | basys3     | Missing   |
| vexriscv           | icecube2-lse             | icebreaker | Missing   |
| vexriscv           | icecube2-lse             | nexys      | Missing   |
| vexriscv           | icecube2-lse             | zybo       | Missing   |
| vexriscv           | icecube2-synpro          | arty       | Missing   |
| vexriscv           | icecube2-synpro          | basys3     | Missing   |
| vexriscv           | icecube2-synpro          | icebreaker | Missing   |
| vexriscv           | icecube2-synpro          | nexys      | Missing   |
| vexriscv           | icecube2-synpro          | zybo       | Missing   |
| vexriscv           | icecube2-yosys           | arty       | Missing   |
| vexriscv           | icecube2-yosys           | basys3     | Missing   |
| vexriscv           | icecube2-yosys           | icebreaker | Missing   |
| vexriscv           | icecube2-yosys           | nexys      | Missing   |
| vexriscv           | icecube2-yosys           | zybo       | Missing   |
| vexriscv           | nextpnr-ice40            | arty       | Missing   |
| vexriscv           | nextpnr-ice40            | basys3     | Missing   |
| vexriscv           | nextpnr-ice40            | icebreaker | Missing   |
| vexriscv           | nextpnr-ice40            | nexys      | Missing   |
| vexriscv           | nextpnr-ice40            | zybo       | Missing   |
| vexriscv           | nextpnr-xilinx           | arty       | Missing   |
| vexriscv           | nextpnr-xilinx           | basys3     | Missing   |
| vexriscv           | nextpnr-xilinx           | icebreaker | Missing   |
| vexriscv           | nextpnr-xilinx           | nexys      | Missing   |
| vexriscv           | nextpnr-xilinx           | zybo       | Missing   |
| vexriscv           | nextpnr-xilinx-fasm2bels | arty       | Missing   |
| vexriscv           | nextpnr-xilinx-fasm2bels | basys3     | Missing   |
| vexriscv           | nextpnr-xilinx-fasm2bels | icebreaker | Missing   |
| vexriscv           | nextpnr-xilinx-fasm2bels | nexys      | Missing   |
| vexriscv           | nextpnr-xilinx-fasm2bels | zybo       | Missing   |
| vexriscv           | radiant-lse              | arty       | Missing   |
| vexriscv           | radiant-lse              | basys3     | Missing   |
| vexriscv           | radiant-lse              | icebreaker | Missing   |
| vexriscv           | radiant-lse              | nexys      | Missing   |
| vexriscv           | radiant-lse              | zybo       | Missing   |
| vexriscv           | radiant-synpro           | arty       | Missing   |
| vexriscv           | radiant-synpro           | basys3     | Missing   |
| vexriscv           | radiant-synpro           | icebreaker | Missing   |
| vexriscv           | radiant-synpro           | nexys      | Missing   |
| vexriscv           | radiant-synpro           | zybo       | Missing   |
| vexriscv           | vivado                   | arty       | Missing   |
| vexriscv           | vivado                   | basys3     | Supported |
| vexriscv           | vivado                   | icebreaker | Missing   |
| vexriscv           | vivado                   | nexys      | Missing   |
| vexriscv           | vivado                   | zybo       | Missing   |
| vexriscv           | vivado-yosys             | arty       | Missing   |
| vexriscv           | vivado-yosys             | basys3     | Supported |
| vexriscv           | vivado-yosys             | icebreaker | Missing   |
| vexriscv           | vivado-yosys             | nexys      | Missing   |
| vexriscv           | vivado-yosys             | zybo       | Missing   |
| vexriscv           | vpr                      | arty       | Missing   |
| vexriscv           | vpr                      | basys3     | Supported |
| vexriscv           | vpr                      | icebreaker | Missing   |
| vexriscv           | vpr                      | nexys      | Missing   |
| vexriscv           | vpr                      | zybo       | Missing   |
| vexriscv           | vpr-fasm2bels            | arty       | Missing   |
| vexriscv           | vpr-fasm2bels            | basys3     | Supported |
| vexriscv           | vpr-fasm2bels            | icebreaker | Missing   |
| vexriscv           | vpr-fasm2bels            | nexys      | Missing   |
| vexriscv           | vpr-fasm2bels            | zybo       | Missing   |
| vexriscv-smp       | icecube2-lse             | arty       | Missing   |
| vexriscv-smp       | icecube2-lse             | basys3     | Missing   |
| vexriscv-smp       | icecube2-lse             | icebreaker | Missing   |
| vexriscv-smp       | icecube2-lse             | nexys      | Missing   |
| vexriscv-smp       | icecube2-lse             | zybo       | Missing   |
| vexriscv-smp       | icecube2-synpro          | arty       | Missing   |
| vexriscv-smp       | icecube2-synpro          | basys3     | Missing   |
| vexriscv-smp       | icecube2-synpro          | icebreaker | Missing   |
| vexriscv-smp       | icecube2-synpro          | nexys      | Missing   |
| vexriscv-smp       | icecube2-synpro          | zybo       | Missing   |
| vexriscv-smp       | icecube2-yosys           | arty       | Missing   |
| vexriscv-smp       | icecube2-yosys           | basys3     | Missing   |
| vexriscv-smp       | icecube2-yosys           | icebreaker | Missing   |
| vexriscv-smp       | icecube2-yosys           | nexys      | Missing   |
| vexriscv-smp       | icecube2-yosys           | zybo       | Missing   |
| vexriscv-smp       | nextpnr-ice40            | arty       | Missing   |
| vexriscv-smp       | nextpnr-ice40            | basys3     | Missing   |
| vexriscv-smp       | nextpnr-ice40            | icebreaker | Missing   |
| vexriscv-smp       | nextpnr-ice40            | nexys      | Missing   |
| vexriscv-smp       | nextpnr-ice40            | zybo       | Missing   |
| vexriscv-smp       | nextpnr-xilinx           | arty       | Missing   |
| vexriscv-smp       | nextpnr-xilinx           | basys3     | Missing   |
| vexriscv-smp       | nextpnr-xilinx           | icebreaker | Missing   |
| vexriscv-smp       | nextpnr-xilinx           | nexys      | Missing   |
| vexriscv-smp       | nextpnr-xilinx           | zybo       | Missing   |
| vexriscv-smp       | nextpnr-xilinx-fasm2bels | arty       | Missing   |
| vexriscv-smp       | nextpnr-xilinx-fasm2bels | basys3     | Missing   |
| vexriscv-smp       | nextpnr-xilinx-fasm2bels | icebreaker | Missing   |
| vexriscv-smp       | nextpnr-xilinx-fasm2bels | nexys      | Missing   |
| vexriscv-smp       | nextpnr-xilinx-fasm2bels | zybo       | Missing   |
| vexriscv-smp       | radiant-lse              | arty       | Missing   |
| vexriscv-smp       | radiant-lse              | basys3     | Missing   |
| vexriscv-smp       | radiant-lse              | icebreaker | Missing   |
| vexriscv-smp       | radiant-lse              | nexys      | Missing   |
| vexriscv-smp       | radiant-lse              | zybo       | Missing   |
| vexriscv-smp       | radiant-synpro           | arty       | Missing   |
| vexriscv-smp       | radiant-synpro           | basys3     | Missing   |
| vexriscv-smp       | radiant-synpro           | icebreaker | Missing   |
| vexriscv-smp       | radiant-synpro           | nexys      | Missing   |
| vexriscv-smp       | radiant-synpro           | zybo       | Missing   |
| vexriscv-smp       | vivado                   | arty       | Supported |
| vexriscv-smp       | vivado                   | basys3     | Missing   |
| vexriscv-smp       | vivado                   | icebreaker | Missing   |
| vexriscv-smp       | vivado                   | nexys      | Missing   |
| vexriscv-smp       | vivado                   | zybo       | Missing   |
| vexriscv-smp       | vivado-yosys             | arty       | Missing   |
| vexriscv-smp       | vivado-yosys             | basys3     | Missing   |
| vexriscv-smp       | vivado-yosys             | icebreaker | Missing   |
| vexriscv-smp       | vivado-yosys             | nexys      | Missing   |
| vexriscv-smp       | vivado-yosys             | zybo       | Missing   |
| vexriscv-smp       | vpr                      | arty       | Missing   |
| vexriscv-smp       | vpr                      | basys3     | Missing   |
| vexriscv-smp       | vpr                      | icebreaker | Missing   |
| vexriscv-smp       | vpr                      | nexys      | Missing   |
| vexriscv-smp       | vpr                      | zybo       | Missing   |
| vexriscv-smp       | vpr-fasm2bels            | arty       | Missing   |
| vexriscv-smp       | vpr-fasm2bels            | basys3     | Missing   |
| vexriscv-smp       | vpr-fasm2bels            | icebreaker | Missing   |
| vexriscv-smp       | vpr-fasm2bels            | nexys      | Missing   |
| vexriscv-smp       | vpr-fasm2bels            | zybo       | Missing   |
+--------------------+--------------------------+------------+-----------+
```

**Comment by ryancj14** [comment]
The last commit adds the functionality to specify project, toolchain, and/or board arguments with --list-combinations to narrow down what you are looking at. Example:
```
$ python3 fpgaperf.py --list-combinations --board basys3 --project baselitex
+-----------+--------------------------+--------+---------+
| Project   | Toolchain                | Board  | Status  |
+-----------+--------------------------+--------+---------+
| baselitex | icecube2-lse             | basys3 | Missing |
| baselitex | icecube2-synpro          | basys3 | Missing |
| baselitex | icecube2-yosys           | basys3 | Missing |
| baselitex | nextpnr-ice40            | basys3 | Missing |
| baselitex | nextpnr-xilinx           | basys3 | Missing |
| baselitex | nextpnr-xilinx-fasm2bels | basys3 | Missing |
| baselitex | radiant-lse              | basys3 | Missing |
| baselitex | radiant-synpro           | basys3 | Missing |
| baselitex | vivado                   | basys3 | Missing |
| baselitex | vivado-yosys             | basys3 | Missing |
| baselitex | vpr                      | basys3 | Missing |
| baselitex | vpr-fasm2bels            | basys3 | Missing |
+-----------+--------------------------+--------+---------+
```
Adding this functionality required me to add to the get_toolchains() and get_projects() functions. I did the best I could, but I would appreciate someone looking over my work in those functions to see if that is the most efficient way of doing what I did.

**Comment by acomodi** [comment]
@ryancj14 Looking at the resulting output, it seems that I didn't take into account that we have so many tests and toolchains that the number of entries in the table is way too exhaustive.

For instance, we are not currently supporting radiant and icecube (they are not being tested in CI right now). We probably want to exclude them from the supported toolchains at the moment.
I would likely comment out these lines below with a `TODO` comment explaining that these are not currently being extensively tested: https://github.com/SymbiFlow/fpga-tool-perf/blob/f4b182beb2a7cc8c34fc2311aefe67615a5de324/fpgaperf.py#L127-L131.

Another check to do to reduce the resulting table would be to add a supported-vendor to the project json. This because I see a lot of repetitions to add the icebreaker board, which is from lattice, but the fact is that many tests are not vendor-agnostic, and they can be built only with vivado.
My suggestion here would be to add an entry to the json, specifying the supported vendors, and, apart from the oneblink test, which can be supported by lattice as well, all the others would be xilinx only.

**Pull request merged**
