### PR TITLE
Update VTR to d6d69ff92

### PR DESCRIPTION
**Pull request by HackerFoo**

### CODE REVIEW

**Comment by HackerFoo** [comment]
The build is failing in the same way as master: https://github.com/SymbiFlow/fpga-tool-perf/issues/289

**Comment by HackerFoo** [comment]
@acomodi @mithro @litghost Could someone please look at this? It's a one line change. Thanks.

**Comment by acomodi** [comment]
@HackerFoo FYI, with https://github.com/SymbiFlow/fpga-tool-perf/pull/290 the vtr version is grabbed from the Symbiflow arch defs package.

**Review by acomodi — APPROVED** [review]
LGTM

**Pull request merged**
