### PR TITLE
nextpnr: Use Conda packages from LiteX-Hub channel

### PR DESCRIPTION
**Pull request by ajelinski**
The packages have been also updated to their latest versions.

### CODE REVIEW

**Comment by ajelinski** [comment]
The PR title and body have been updated because `conf/symbiflow/environment.yml` already uses packages from the LiteX-Hub channel on the `master` branch. Therefore the commit has been modified to only change `conf/nextpnr/environment.yml` and placed on top of the current `master`.

**Comment by ajelinski** [comment]
I have rebased branch onto the current master. Packages' versions were modified to have the packages as close to the ones used in the latest successfully tested commit on `master` as possible. I hope this will make the kokoro testing successful.

**Comment by ajelinski** [comment]
I've added a commit to lock `python-fpga-interchange` package revision to the one before using `rapidyaml` which turns out to be very problematic: https://github.com/SymbiFlow/python-fpga-interchange/issues/19 .

This should also fix CI on master as it fails exactly because of it.

**Comment by ajelinski** [comment]
I guess it should @mithro. I can see there even is a PR pending: https://github.com/SymbiFlow/prjxray/pull/1550 but it seems forgotten. If it isn't merged until I get this PR green, I'll add the URL as a comment.

**Comment by mithro** [comment]
Do you need me for something here?

**Pull request merged**
