### PR TITLE
kokoro: setup initial configurations

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR adds kokoro configurations to run the tests

### CODE REVIEW

**Comment by acomodi** [comment]
@mithro FYI

**Comment by mithro** [comment]
@acomodi - It helps kokoro run if I actually install the webhook which makes it listen to this repository.

**Comment by mithro** [comment]
Since I wasn't able to push to this repository, I have instead create a pull request at https://github.com/SymbiFlow/fpga-tool-perf/pull/58

**Comment by mithro** [comment]
@acomodi this has been merged now see https://github.com/SymbiFlow/fpga-tool-perf/pull/58

**Pull request closed without merging**
